CREATE SCHEMA CLINICA

CREATE TABLE CLINICA.MEDICO(
	ID_MEDICO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME TEXT NOT NULL,
	CRM TEXT NOT NULL,
	ESPECIALIDADE TEXT NOT NULL
);

CREATE TABLE CLINICA.PACIENTE(
	ID_PACIENTE INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CPF VARCHAR(11) NOT NULL,
	NOME_COMPLETO TEXT NOT NULL,
	IDADE TEXT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);

ALTER TABLE CLINICA.PACIENTE
ADD CONSTRAINT CPF UNIQUE (CPF);

CREATE TABLE CLINICA.CLINICA(
	ID_CLINICA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME TEXT NOT NULL,
	ENDERECO TEXT NOT NULL,
	DESCRICAO TEXT
);

CREATE TABLE CLINICA.CONSULTA(
	ID_CONSULTA INT GENERATED ALWAYS AS IDENTITY,
	DATA_CONSULTA TIMESTAMPTZ NOT NULL,
	VALOR NUMERIC(10,4),
	ID_MEDICO INT NOT NULL,
	ID_CLINICA INT NOT NULL,
	ID_PACIENTE INT NOT NULL,
	FOREIGN KEY (ID_MEDICO) REFERENCES CLINICA.MEDICO(ID_MEDICO),
	FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA.CLINICA(ID_CLINICA),
	FOREIGN KEY (ID_PACIENTE) REFERENCES CLINICA.PACIENTE (ID_PACIENTE)
);

ALTER TABLE CLINICA.CONSULTA
ADD CONSTRAINT ID_CONSULTA PRIMARY KEY (ID_CONSULTA);