CREATE SCHEMA ECOMMERCE

CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY,
	NOME_COMPLETO TEXT NOT NULL,
	EMAIL TEXT,
	SENHA TEXT NOT NULL,
	TELEFONE TEXT NOT NULL,
	DATA_CADASTRO TIMESTAMPTZ NOT NULL
);

CREATE TABLE ENDERECO_DE_ENTREGA(
	ID_ENDERECO INT 
	ID_CLIENTE INT NOT NULL REFERENCES ECOMMERCE.CLIENTE(ID_CLIENTE)
	LOGRADOURO TEXT NOT NULL,
	NUMERO CHAR(10) NOT NULL,
	COMPLEMENTO TEXT,
	BAIRRO TEXT NOT NULL,
	CIDADE TEXT NOT NULL,
	ESTADO TEXT NOT NULL,
	CEP TEXT NOT NULL,
);

CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY,
	ID_CLIENTE INT NOT NULL REFERENCES ECOMMERCE.CLIENTE(ID_CLIENTE),
	DATA_PEDIDO TIMESTAMPTZ NOT NULL,
	VALOR_TOTAL NUMERIC(10,4) NOT NULL,
	STATUS TEXT NOT NULL,
	ID_ENDERECO TEXT NOT NULL REFERENCES ECOMMERCE.ENDERECO_DE_ENTREGA(ID_ENDERECO)
);

CREATE TABLE CATEGORIA (
	ID_CATEGORIA INT,
	NOME_CATEGORIA TEXT NOT NULL,
	DESCRICAO TEXT,
);

CREATE TABLE PRODUTO(
	ID_PRODUTO TEXT NOT NULL,
	NOME_PRODUTO TEXT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	PRECO NUMERIC(10,4) NOT NULL,
	ESTOQUE_DISPONIVEL INT NOT NULL,
	IMAGEM_URL TEXT,
	ID_CATEGORIA INT NOT NULL REFERENCES ECOMMERCE.CATEGORIA(ID_CATEGORIA)
);













