CREATE SCHEMA ECOMMERCE

CREATE TABLE ECOMMERCE.CLIENTE(
	ID_CLIENTE INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME_COMPLETO TEXT NOT NULL,
	EMAIL TEXT UNIQUE,
	SENHA TEXT NOT NULL,
	TELEFONE TEXT NOT NULL,
	DATA_CADASTRO TIMESTAMPTZ NOT NULL
);

CREATE TABLE ECOMMERCE.CATEGORIA (
	ID_CATEGORIA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME_CATEGORIA TEXT NOT NULL,
	DESCRICAO TEXT NULL
);

CREATE TABLE ECOMMERCE.ENDERECO_DE_ENTREGA(
	ID_ENDERECO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_CLIENTE INT NOT NULL REFERENCES ECOMMERCE.CLIENTE(ID_CLIENTE),
	LOGRADOURO TEXT NOT NULL,
	NUMERO CHAR(10) NOT NULL,
	COMPLEMENTO TEXT NULL,
	BAIRRO TEXT NOT NULL,
	CIDADE TEXT NOT NULL,
	ESTADO TEXT NOT NULL,
	CEP TEXT NOT NULL
);

CREATE TABLE ECOMMERCE.PEDIDO(
	ID_PEDIDO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_CLIENTE INT NOT NULL REFERENCES ECOMMERCE.CLIENTE(ID_CLIENTE),
	DATA_PEDIDO TIMESTAMPTZ NOT NULL,
	VALOR_TOTAL NUMERIC(10,4) NOT NULL,
	STATUS TEXT NOT NULL,
	ID_ENDERECO INT NOT NULL REFERENCES ECOMMERCE.ENDERECO_DE_ENTREGA(ID_ENDERECO)
);

CREATE TABLE ECOMMERCE.PRODUTO(
	ID_PRODUTO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME_PRODUTO TEXT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	PRECO NUMERIC(10,4) NOT NULL,
	ESTOQUE_DISPONIVEL INT NOT NULL,
	IMAGEM_URL TEXT,
	ID_CATEGORIA INT NOT NULL REFERENCES ECOMMERCE.CATEGORIA(ID_CATEGORIA)
);
CREATE TABLE ECOMMERCE.ITEM_DO_PEDIDO(
	ID_ITEM INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_PEDIDO INT NOT NULL REFERENCES ECOMMERCE.PEDIDO(ID_PEDIDO),
	ID_PRODUTO INT NOT NULL REFERENCES ECOMMERCE.PRODUTO(ID_PRODUTO),
	QUANTIDADE INT NOT NULL
);

CREATE TABLE ECOMMERCE.PAGAMENTO(
	ID_PAGAMENTO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_PEDIDO INT NOT NULL REFERENCES ECOMMERCE.PEDIDO(ID_PEDIDO),
	FORMA_PAGAMENTO TEXT NOT NULL,
	STATUS TEXT NOT NULL,
	DATA_PAGAMENTO TIMESTAMPTZ NOT NULL
);














