--INTERMEDIARIO 1 Junção Simples (JOIN)
SELECT
	ID_PEDIDO,
	NOME_COMPLETO
FROM ECOMMERCE.PEDIDO
JOIN
	ECOMMERCE.CLIENTE
ON ECOMMERCE.PEDIDO.ID_CLIENTE = ECOMMERCE.CLIENTE.ID_CLIENTE;

--INTERMIDIARIO 2 Junção com Filtro
SELECT
	ECOMMERCE.PEDIDO.ID_PEDIDO,
	ECOMMERCE.PRODUTO.ID_PRODUTO,
	ECOMMERCE.PRODUTO.NOME_PRODUTO
FROM ECOMMERCE.ITEM_DO_PEDIDO
JOIN
	ECOMMERCE.PEDIDO
ON	ECOMMERCE.PEDIDO.ID_PEDIDO = ECOMMERCE.ITEM_DO_PEDIDO.ID_PEDIDO

JOIN
	ECOMMERCE.PRODUTO
ON	ECOMMERCE.PRODUTO.ID_PRODUTO = ECOMMERCE.ITEM_DO_PEDIDO.ID_PRODUTO

WHERE ECOMMERCE.PEDIDO.ID_PEDIDO = 1;


